### ISSUE TITLE
Add support for player parties

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-initiative-tracker#27]

**Comment by ObsidianTTRPGProject** [comment]
So some ideas on how this would be useful. 

1. Ability to define a party and assign players to that party. 
2. Ability to set the active party so you can swap. 

However...

3. Ability to enable/disable certain players with a party. 

Use case:
I run 3x groups using the same vault. So everytime we switch I currently need to delete and recreate the Initiative Tracker config. 
One of my groups is too large to run them all at the table at the same time but not large enough to split into two groups. We have floaters and due to COVID restrictions we have people who sub out (10 person per house limit). So ability to disable some characters and enable others would be really useful. 

No idea how possible this is... But you're the one with the wizard hat ;-)

**Comment by Sklore** [comment]
So some ideas on how this would be useful.

Ability to define a party and assign players to that party.
Ability to set the active party so you can swap.
However...

Ability to enable/disable certain players with a party.
Use case:
I run 3x groups using the same vault. So everytime we switch I currently need to delete and recreate the Initiative Tracker config.
One of my groups is too large to run them all at the table at the same time but not large enough to split into two groups. We have floaters and due to COVID restrictions we have people who sub out (10 person per house limit). So ability to disable some characters and enable others would be really useful.

No idea how possible this is... But you're the one with the wizard hat ;-)

**Comment by valentine195** [comment]
Closed in 7.2.0
